-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-01-05 12:31:03 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE bilet (
    bilet_id     NUMBER NOT NULL,
    pret         NUMBER(4, 2) NOT NULL,
    eveniment_id NUMBER NOT NULL
);

ALTER TABLE bilet ADD CONSTRAINT bilet_pret_ck CHECK ( pret < 2000 );

ALTER TABLE bilet ADD CONSTRAINT bilet_pk PRIMARY KEY ( bilet_id );

CREATE TABLE eveniment (
    eveniment_id NUMBER NOT NULL,
    nume         VARCHAR2(30) NOT NULL
);

ALTER TABLE eveniment ADD CONSTRAINT eveniment_pk PRIMARY KEY ( eveniment_id );

CREATE TABLE portofel (
    suma        NUMBER(9, 2),
    suporter_id NUMBER NOT NULL
);

CREATE UNIQUE INDEX portofel__idx ON
    portofel (
        suporter_id
    ASC );

CREATE TABLE sup_even_fk (
    suporter_suporter_id   NUMBER NOT NULL,
    eveniment_eveniment_id NUMBER NOT NULL
);

ALTER TABLE sup_even_fk ADD CONSTRAINT sup_even_fk_pk PRIMARY KEY ( suporter_suporter_id,
                                                                    eveniment_eveniment_id );

CREATE TABLE suporter (
    suporter_id NUMBER NOT NULL,
    nume        VARCHAR2(30) NOT NULL,
    email       VARCHAR2(30) NOT NULL,
    nrtelefon   VARCHAR2(10)
);

ALTER TABLE suporter
    ADD CONSTRAINT suporter_email_ck CHECK ( REGEXP_LIKE ( email,
                                                           '[a-z0-9._%-]+@[a-z0-9._%-]+\.[a-z]{2,4}' ) );

ALTER TABLE suporter
    ADD CONSTRAINT suporter_nrtelefon_ck CHECK ( length(nrtelefon) = 10 );

ALTER TABLE suporter ADD CONSTRAINT suporter_pk PRIMARY KEY ( suporter_id );

ALTER TABLE suporter ADD CONSTRAINT id_name_uk UNIQUE ( suporter_id,
                                                        nume );

ALTER TABLE bilet
    ADD CONSTRAINT even_bilet_fk FOREIGN KEY ( eveniment_id )
        REFERENCES eveniment ( eveniment_id );

ALTER TABLE sup_even_fk
    ADD CONSTRAINT sup_even_fk_eveniment_fk FOREIGN KEY ( eveniment_eveniment_id )
        REFERENCES eveniment ( eveniment_id );

ALTER TABLE sup_even_fk
    ADD CONSTRAINT sup_even_fk_suporter_fk FOREIGN KEY ( suporter_suporter_id )
        REFERENCES suporter ( suporter_id );

ALTER TABLE portofel
    ADD CONSTRAINT sup_port_fk FOREIGN KEY ( suporter_id )
        REFERENCES suporter ( suporter_id );

CREATE SEQUENCE bilet_bilet_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER bilet_bilet_id_trg BEFORE
    INSERT ON bilet
    FOR EACH ROW
    WHEN ( new.bilet_id IS NULL )
BEGIN
    :new.bilet_id := bilet_bilet_id_seq.nextval;
END;
/

CREATE SEQUENCE eveniment_eveniment_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER eveniment_eveniment_id_trg BEFORE
    INSERT ON eveniment
    FOR EACH ROW
    WHEN ( new.eveniment_id IS NULL )
BEGIN
    :new.eveniment_id := eveniment_eveniment_id_seq.nextval;
END;
/

CREATE SEQUENCE suporter_suporter_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER suporter_suporter_id_trg BEFORE
    INSERT ON suporter
    FOR EACH ROW
    WHEN ( new.suporter_id IS NULL )
BEGIN
    :new.suporter_id := suporter_suporter_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             1
-- ALTER TABLE                             12
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           3
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          3
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
